CREATE DATABASE IF NOT EXISTS DotnetJwtAuth;
USE DotnetJwtAuth;

CREATE TABLE IF NOT EXISTS User (
    UserId BIGINT NOT NULL AUTO_INCREMENT,
    Username VARCHAR(50) NOT NULL,
    Email VARCHAR(320) NOT NULL,
    PasswordHash BINARY(64) NOT NULL,
    PasswordSalt BINARY(64) NOT NULL,
    UserCreateDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UserModifiedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (UserId)
);

