CREATE DATABASE IF NOT EXISTS DotnetJwtAuth;
USE DotnetJwtAuth;

CREATE TABLE IF NOT EXISTS User (
    UserId BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(50) NOT NULL,
    Email VARCHAR(320) NOT NULL,
    PasswordHash BINARY(64) NOT NULL,
    PasswordSalt BINARY(64) NOT NULL,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    UserCreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UserModifiedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Project (
    ProjectId BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(50) NOT NULL,
    Content LONGTEXT CHARACTER SET utf8mb4,
    UserId BIGINT NOT NULL,
    ProjectCreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ProjectModifiedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY FK_UserId(UserId) REFERENCES User(UserId) ON UPDATE CASCADE ON DELETE CASCADE
);
