const baseUrl = 'http://localhost:5000';

export const apiConstants = {
    'baseUrl': baseUrl,
    'projectsController': `${baseUrl}/projects`,
    'projectsHub': `${baseUrl}/hubs/projects`,
    'usersController': `${baseUrl}/users`,
    'usersHub': `${baseUrl}/hubs/users`,
};

export const authConstants = {
    'AUTH_LOCAL_STORAGE_KEY': 'AUTH_LOCAL_STORAGE',

    'LOGIN': 'LOGIN',
    'LOGIN_SUCCESS': 'LOGIN_SUCCESS',
    'LOGIN_ERROR': 'LOGIN_ERROR',

    'LOGOUT': 'LOGOUT',

    'REFRESH_TOKEN': 'REFRESH_TOKEN',
    'REFRESH_TOKEN_SUCCESS': 'REFRESH_TOKEN_SUCCESS',
    'REFRESH_TOKEN_ERROR': 'REFRESH_TOKEN_ERROR',

    'CREATE_NEW_USER': 'CREATE_NEW_USER',
    'CREATE_NEW_USER_SUCCESS': 'CREATE_NEW_USER_SUCCESS',
    'CREATE_NEW_USER_ERROR': 'CREATE_NEW_USER_ERROR',
};

export const projectConstants = {
    'RECENT_PROJECTS_LOCAL_STORAGE_KEY': 'RECENT_PROJECTS_LOCAL_STORAGE_KEY',
    'RECENT_PROJECTS_LAST_POLL_DATE_STORAGE_KEY': 'RECENT_PROJECTS_LAST_POLL_DATE_STORAGE_KEY',

    'CREATE_PROJECT': 'CREATE_PROJECT',
    'CREATE_PROJECT_SUCCESS': 'CREATE_PROJECT_SUCCESS',
    'CREATE_PROJECT_ERROR': 'CREATE_PROJECT_ERROR',

    'READ_PROJECT': 'READ_PROJECT',
    'READ_PROJECT_SUCCESS': 'READ_PROJECT_SUCCESS',
    'READ_PROJECT_ERROR': 'READ_PROJECT_ERROR',

    'READ_PROJECTS_MODIFIED_AFTER_DATE': 'READ_PROJECTS_MODIFIED_AFTER_DATE',
    'READ_PROJECTS_MODIFIED_AFTER_DATE_SUCCESS': 'READ_PROJECTS_MODIFIED_AFTER_DATE_SUCCESS',
    'READ_PROJECTS_MODIFIED_AFTER_DATE_ERROR': 'READ_PROJECTS_MODIFIED_AFTER_DATE_ERROR',
};

export const notificationConstants = {
    'NOTIFY_PROJECT_CREATED': 'NOTIFY_PROJECT_CREATED',
    'NOTIFY_PROJECT_CREATED_SUCCESS': 'NOTIFY_PROJECT_CREATED_SUCCESS',
    'NOTIFY_PROJECT_CREATED_ERROR': 'NOTIFY_PROJECT_CREATED_ERROR',

    'RECEIVE_PROJECT_CREATED': 'RECEIVE_PROJECT_CREATED',
    'PROJECT_SUBSCRIBERS_GROUP_NAME': 'CREATED_PROJECTS_SUBSCRIBERS',
    'PROJECT_SUBSCRIBERS_ADD_TO_GROUP_RPC': 'AddToGroup',

    'NOTIFY_USER_CREATED': 'NOTIFY_USER_CREATED',
    'NOTIFY_USER_CREATED_SUCCESS': 'NOTIFY_USER_CREATED_SUCCESS',
    'NOTIFY_USER_CREATED_ERROR': 'NOTIFY_USER_CREATED_ERROR',

    'RECEIVE_USER_CREATED': 'RECEIVE_USER_CREATED',
    'USER_SUBSCRIBERS_GROUP_NAME': 'CREATED_USER_SUBSCRIBERS',
    'USER_SUBSCRIBERS_ADD_TO_GROUP_RPC': 'AddToGroup',

    'SUBSCRIBE_PROJECT_HUB': 'SUBSCRIBE_PROJECT_HUB',
    'SUBSCRIBE_PROJECT_HUB_SUCCESS': 'SUBSCRIBE_PROJECT_HUB_SUCCESS',
    'SUBSCRIBE_PROJECT_HUB_ERROR': 'SUBSCRIBE_PROJECT_HUB_ERROR',

    'UNSUBSCRIBE_PROJECT_HUB': 'UNSUBSCRIBE_PROJECT_HUB',
    'UNSUBSCRIBE_PROJECT_HUB_SUCCESS': 'UNSUBSCRIBE_PROJECT_HUB_SUCCESS',
    'UNSUBSCRIBE_PROJECT_HUB_ERROR': 'UNSUBSCRIBE_PROJECT_HUB_ERROR',

    'PROJECT_NOTIFICATION_HANDLER_NAME': 'ProjectNotification',

    'SUBSCRIBE_USER_HUB': 'SUBSCRIBE_USER_HUB',
    'SUBSCRIBE_USER_HUB_SUCCESS': 'SUBSCRIBE_USER_HUB_SUCCESS',
    'SUBSCRIBE_USER_HUB_ERROR': 'SUBSCRIBE_USER_HUB_ERROR',

    'UNSUBSCRIBE_USER_HUB': 'UNSUBSCRIBE_USER_HUB',
    'UNSUBSCRIBE_USER_HUB_SUCCESS': 'UNSUBSCRIBE_USER_HUB_SUCCESS',
    'UNSUBSCRIBE_USER_HUB_ERROR': 'UNSUBSCRIBE_USER_HUB_ERROR',

    'USER_NOTIFICATION_HANDLER_NAME': 'UserNotification',

    'VISIBLE_LIMIT': 3,
};

export const persistenceConstants = {
    'LOCAL_STORAGE_STRATEGY': 'LOCAL_STORAGE_STRATEGY',
    'COOKIE_CRUMB_STRATEGY': 'COOKIE_CRUM_STRATEGY',

    'TIER_A': 1,
    'TIER_B': 2,
    'TIER_C': 3,
    'TIER_D': 4,
    'TIER_E': 5,

    'INDEX_KEY': 'INDEX_KEY',
    'LAST_ACCESSED_KEY': 'LAST_ACCESSED_KEY',
    'MAX_COOKIE_WRITE_ATTEMPTS': 8,

    // Expire 'Tier A' after 30 days
    'EXPIRATION_MILLISECONDS_TIER_A': 30 * 24 * 60 * 60 * 1000,
    // Expire 'Tier B' after 14 days
    'EXPIRATION_MILLISECONDS_TIER_B': 14 * 24 * 60 * 60 * 1000,
    // Expire 'Tier C' after 7 days
    'EXPIRATION_MILLISECONDS_TIER_C': 7 * 24 * 60 * 60 * 1000,
    // Expire 'Tier D' after 1 day
    'EXPIRATION_MILLISECONDS_TIER_D': 1 * 24 * 60 * 60 * 1000,
    // Expire 'Tier E' after 1 hour
    'EXPIRATION_MILLISECONDS_TIER_E': 1 * 60 * 60 * 1000,
};
